### ISSUE TITLE
User Story - Display Genetic History

### ISSUE THREAD

**Issue by WyattHolliday** [MylesScholz/A-Life-Capstone-Project#10]
### Motivation
As a casual user I want to have a chart that shows me the genetic history of the organisms so that I can better see and understand what happened in the simulation.

This feature will provide for the opportunity to see where the species diverged from there common ancestors and the path that they took throughout the simulation. It will provide way for us to display the results of many simulations in a visually appealing to all and help new users quickly understand how the simulation works. We do have all of the data to create this feature in the genomes of the organisms and we can display it based on their genetic similarity.

### Requirements
* Result in the creation of a chart that represents the genetic change of the organisms and their offspring during the simulation
* Species should be spaced out far enough to visually tell the difference
* Apon the creation of a new species the color should start changing giving each a different color
* User should be able to save and download this chart

### Dependencies
* A standard genome must be developed first
* The database should be in place

### Subtasks
* Create algorithm to determine genetic similarity
* Create system to map onto chart

### Time Estimate
A rough estimate of 15 - 25 hours

### Open Questions
* Should the graph be calculated as the simulation is running?

### Acceptance Criteria
* All requirements are met
* All subtasks have been done
* Functionality has been implemented and is accessible in the simulation using the data created by the simulation
* System has been tested on a computer running overnight to see if results are satisfactory

### Definition of Done
* Meets all acceptance criteria
* All of the unit, integration and other tests pass
* All documentation is updated
* A pull request is created and it is merged to main

**Comment by MylesScholz** [comment]
I am closing this issue in order to combine it into #15 User will be able to view statistics about the simulation.
