### ISSUE TITLE
Simulation Source (ver 0.1.0)

### ISSUE THREAD

**Issue by EatYoCharms9** [MylesScholz/A-Life-Capstone-Project#14]
### Description
Working initial version (0.1.0) of genome and simulation environment with the **most basic** required features. The simulation environment should include some nodes, the ability for "time" to pass, and at least one specified interaction (or rule) which occurs between the nodes over time. Has a basic readout which tells the number of nodes and marks the interactions which have occurred.

### Dependencies
- Select simulation framework (unless created in backend source for portability)
- Select simulation source language
- Testing framework (decide parameters for efficiency and emerging behaviors)
- Version control system setup

### Time Estimate
- End of academic term (December 15)

### Acceptance Criteria
- The genome and simulation environment must be operational in its basic form.
- Version 0.1.0 should be tagged and documented as the initial working version.
- The environment should successfully initialize with a specified number of nodes.
- Implementation of a time progression mechanism where "time" can be tracked and visualized within the simulation.
- At least one type of specified interaction or rule must be clearly implemented and functional between the nodes.
- This interaction should be observable and should change according to the passage of time within the simulation.
- The system should provide a basic readout or dashboard.
- This readout must display the total number of nodes at any given time.
- All interactions or significant events occurring between nodes should be logged or marked in the readout in real-time or as a summary.

**Comment by MylesScholz** [comment]
I am closing this issue because version 0.1.0 has been released and verified by the project partner.
