### ISSUE TITLE
Ver. 0.1.0 Implement a basic Start Button UI

### ISSUE THREAD

**Issue by EthanD1998** [MylesScholz/A-Life-Capstone-Project#28]
### Motivation
We want to user to be able to control parts of the simulation through basic UI such as playback controls. For Ver. 0.1.0 this consists of a basic start button.

### Description
- When the simulation first opens the start button will be visible.
- When the button is pressed it will spawn cells based on the number set in the cell spawner
- After the Cells are spawned the button will disappear so the user can't create more cells.

### Dependencies
None

### Time Estimate
2.5 person-hours of work.

### Acceptance Criteria
* All requirements are satisfied in a released version of the program
* The project partner has accepted the released version

**Comment by MylesScholz** [comment]
I am closing this issue because the associated pull request has merged with main.
