### ISSUE TITLE
Update GDExtension to 4.2

### ISSUE THREAD

**Issue by Alex-x90** [MylesScholz/A-Life-Capstone-Project#44]
### Motivation
Since we've updated our project to Godot 4.2, we should also update GDExtension to 4.2.

### Description
Update the godot-cpp submodule to the 4.2 branch and fix issues that occur because of this, if any.

### Dependencies
* [Automatic builds](https://github.com/MylesScholz/A-Life-Capstone-Project/pull/42) to verify it works across all builds

### Time Estimate
1 person-hour of work

### Acceptance Criteria
* Godot-cpp submodule updated to 4.2 branch
* Builds succeed

**Comment by MylesScholz** [comment]
I am closing this issue because the acceptance criteria are met.
