### ISSUE TITLE
Cells leave nutrient zones upon death

### ISSUE THREAD

**Issue by WyattHolliday** [MylesScholz/A-Life-Capstone-Project#86]
### Motivation
Cells are made up of resources that other cells can use to grow. So, when cells die, they should spawn a nutrient zone to represent that.

### Description
Create a signal that triggers when a cell dies and that is picked up by the CellEnvironment. In the CellEnvironment callback, it should create a NutrientZone of roughly the same size as the Cell that died. You will have to figure out what the conversion rate between the Cell scale and NutrientZone scales is. The NutrientZone should have the same number of nutrients as the Cell and a regeneration rate of zero. Also, you should modify the NutrientZone class to have an option to delete itself when it runs out of nutrients, and that option should be enabled for the NutrientZones that are left by dead Cells.

### Acceptance Criteria
All cells spawn a NutrientZone upon death with the listed attributes determined by the cell that died
The NutrientZone deletes itself when it runs out of nutrients
The changes are pushed to a feature branch and a pull request is created

**Comment by MylesScholz** [comment]
I am closing this Issue because the changes are merged to main.
