### ISSUE TITLE
User Story - Organism info interface

### ISSUE THREAD

**Issue by EthanD1998** [MylesScholz/A-Life-Capstone-Project#9]
### Background

User Story: As a user interested in genetics, I want to be able to see and edit the genetic code of any of the organisms being simulated in the application, so that I can see the effects of the genetic code on how an organism is created.

The objective above applies to any user interested in the interactions that genetic code has on the creation of organisms. This could be researchers, students, professors, or just people interested in the subject. Overall we want our application to be a more realistic simulation that people could use to learn about the subject.

### Requirements

- The user should be able to select an organism that they see on screen and see some information on that organism, including what genetic code that organism has. 
- The user should then be able to access more specifics on the genetic code and be able to adjust it and save.
- The system should see the change in genetic code once its been saved and change the organism to match the new code.

###  Dependencies 

This work item depends on the selection of a framework #1 and simulation playback controls #7

### Sub-tasks

- Create a UI popup for when an organism is selected.
- Create a UI for looking at the full genetic code and editing it.

### Time Estimate

This item should take 15-20 person-hours of work

### Open Questions

- How should the genetic code be displayed?
Should the data be displayed in a nice graphic or just in some basic editable text?
Should we display what part of the organism each piece of genetic code correlates to?

### Acceptance Criteria

Users can click on an organism to find out more information on that organism and be able to inspect the genetic code and edit it.

### Definition of Done

- All unit, integration, and other tests pass
- Branches are merged into main via an approved pull request
- Documentation is updated, including comments within the code and on the release notes

**Comment by MylesScholz** [comment]
I am closing this issue in order to combine it into #15 User will be able to view statistics about the simulation.
